server-type: MULTI_ARENA
bungee-cord: false
alt-color-code: '&'
is-prefix: true
prefix: '&e[&6MinigamesDevelopmentKit&e] '

files-path:
  config-path: ''
  language-path: 'Language'

database:
  type: SQLite
  database: database
  host: host
  user: user
  password: password
  port: 3306
  ssl: true
  local-database-file: database
  database-fail-event: CONNECT_TO_DEFAULT_DISABLE